version: '3.8'

services:
  app:
    build: .
    container_name: task-manager-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/taskdb?sslmode=disable
      - REDIS_URL=redis:6379
      - JWT_SECRET=supersecretkey

  db:
    image: postgres:15
    container_name: task-manager-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: task-manager-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: